apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: vote
spec:
  replicas: 5
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: vinycoolguy/vote:main-4d1dc291-1755239995
          envFrom:
            - configMapRef:
                name: vote
                optional: true
