apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ingress.yaml
patchesStrategicMerge:
- deployment.yaml
- service.yaml
namespace: instavote
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "vinayak@gmail.com"
images:
- name: vinycoolguy/vote
  newTag: main-9c71b14b-1755249042 # {"$imagepolicy": "flux-system:vote:tag"}
configMapGenerator:
- name: vote
  literals:
  - OPTION_A=Summer
  - OPTION_B=Winter
